project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "NorEden"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: documentation/index.qmd
        text: Documentation
 
      - href: software/index.qmd
        text: Software

      - href: archive/index.qmd
        text: Archive
        
      #- href: about.qmd
      #  text: About

    right:
      - icon: tag
        text: Issues
        href: https://github.com/ocbe-uio/noreden_doc/issues

      - icon: github
        text: GitHub
        href: https://github.com/ocbe-uio/noreden_doc


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



