---
title: "Package development log"
format: 
  html:
    code-fold: false
    code-tools: false
editor: source
---

[Flowchart](https://lucid.app/lucidchart/d6c17246-dc1c-4d8a-8966-9ccebea58097/edit?viewport_loc=-124%2C-1115%2C1343%2C819%2C0_0&invitationId=inv_4bec6628-1d54-4d4e-b322-d6e9fe2c7c30) for the implementation.

## Overview

The core functionalities contain the following steps:

* provide food data
* compute inequality constraints (based on current total contribution from the existing diet)
* algorithm to find the new diet
* result processing and presentation

The existing implementation is fixed: not functionalized. The target implementation should allow flexibility at each step.


### Provide food data



### Compute inequality constraints 

The default inequality constraints are based on the **current total contribution**: 

* current diet (d)
* contrib per unit for each target outcome (e.g. ghge, energy)
* option to scale / standardize

Inequality constraints depend on the above, plus the coefficients to set upper and lower. Probably a good idea to split upper and lower.



### Optimization algorithm

This step requires better **functional programming**: need to wrap the functions to generate multiple inequality formulae. 

### Output processing












